apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgeserver
spec:
  selector:
      matchLabels:
        app: forgeserver
  replicas: 1
  template:
      metadata:
        labels:
            app: forgeserver
      spec:
        containers:
        - name: forgemonserver
          image: itzg/minecraft-server
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2512Mi"
              cpu: "1500m"
            limits:
              memory: "2512Mi"
              cpu: "1500m"
          ports:
          - containerPort: 25565
          env:
          - name: "MEMORY"
            value: "1500M"
          - name: EULA
            value: "TRUE"
          - name: TYPE
            value: "FORGE"
          - name: VERSION
            value: "1.18.1"
          - name: "level-seed"
            value: "-1766999811"
          - name: server-name
            value: "Forge"
          - name: motd
            value: "Forge Minecraft Server"
          - name: OPS
            value: "AHollowKnightFan"
          volumeMounts:
          - mountPath: "/data"
            name: volume
        volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: forgeserver-disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgeserver-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: forgeserver
spec:
  selector:
    app: forgeserver
  ports:
  - protocol: TCP
    port: 25565
    targetPort: 25565
  type: LoadBalancer
