apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraftserver
  namespace: minecraft
spec:
  selector:
      matchLabels:
        app: minecraftserver
  replicas: 1
  template:
      metadata:
        labels:
            app: minecraftserver
      spec:
        containers:
        - name: minecraftserver
          image: itzg/minecraft-server:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1024Mi"
              cpu: "100m"
            limits:
              memory: "1512Mi"
              cpu: "1000m"
          ports:
          - containerPort: 25565
          env:
          - name: EULA
            value: "TRUE"
          - name: TZ
            value: "Europe/London"
          - name: SERVER_NAME
            value: "Turbocraft"
          - name: MOTD
            value: "E G G"
          - name: ICON
            value: "https://cloudtech10.blob.core.windows.net/assets/goldapple.jpg"
          - name: WHITELIST
            value: "TurboTom911,ilikecheesecake,Meme_Master_OJ"
          - name: OPS
            value: "TurboTom911"
          - name: motd
            value: "Turbo Minecraft Server"
          volumeMounts:
          - mountPath: "/data"
            name: volume
        volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: minecraftserver-disk
